current_theme = ""
current_locale = "en-US"
root_directory = 'C:\Users\Admin\Desktop\Test'
sorting_enabled = true
overwrite_existing = true
watch_status = false
purge_empty_directories = false

[[sorting_rules]]
destination = "Docs"

[sorting_rules.criterion.ByExtension]
extensions = [
    "pptx",
    "docx",
    "txt",
    "pdf",
]

[[sorting_rules]]
destination = "Images"

[sorting_rules.criterion.ByExtension]
extensions = [
    "png",
    "jpg",
    "webp",
    "bmp",
]

[[sorting_rules]]
destination = "Archives"

[sorting_rules.criterion.ByExtension]
extensions = [
    "rar",
    "zip",
]

[[journal.entries]]
time = "2026-05-04T17:59:17.139100+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\1. შემთხვევის გარჩევა - მეგი გუბელაძე, რაულ ბაირამოვი (1).docx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\1. შემთხვევის გარჩევა - მეგი გუბელაძე, რაულ ბაირამოვი (1).docx'

[[journal.entries]]
time = "2026-05-04T17:59:17.139112200+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\1000117816.jpg'
destination = 'C:\Users\Admin\Desktop\Test\Images\1000117816.jpg'

[[journal.entries]]
time = "2026-05-04T17:59:17.139123300+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\1000117817.jpg'
destination = 'C:\Users\Admin\Desktop\Test\Images\1000117817.jpg'

[[journal.entries]]
time = "2026-05-04T17:59:17.139133800+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\53e3d1a2-9b6a-4344-8103-1f3e5eca9198.pptx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\53e3d1a2-9b6a-4344-8103-1f3e5eca9198.pptx'

[[journal.entries]]
time = "2026-05-04T17:59:17.139144600+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\591446117_4275469972774318_1104650109329468696_n.webp'
destination = 'C:\Users\Admin\Desktop\Test\Images\591446117_4275469972774318_1104650109329468696_n.webp'

[[journal.entries]]
time = "2026-05-04T17:59:17.139154600+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\5ccb78d5-af3a-416d-9208-a032309ff6e7.pptx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\5ccb78d5-af3a-416d-9208-a032309ff6e7.pptx'

[[journal.entries]]
time = "2026-05-04T17:59:17.139164300+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\79355488-d1ea-49fa-bdf6-ae7898fa123d.pptx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\79355488-d1ea-49fa-bdf6-ae7898fa123d.pptx'

[[journal.entries]]
time = "2026-05-04T17:59:17.139175600+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\8-10_კახი გობეჯიშვილი_რაულ ბაირამოვი.docx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\8-10_კახი გობეჯიშვილი_რაულ ბაირამოვი.docx'

[[journal.entries]]
time = "2026-05-04T17:59:17.139186+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\96ea6b23-5a79-4a04-b54f-0e8aceb88d31.pptx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\96ea6b23-5a79-4a04-b54f-0e8aceb88d31.pptx'

[[journal.entries]]
time = "2026-05-04T17:59:17.139196500+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\9969d973-155f-43a8-852b-43b0596f8f5d.pptx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\9969d973-155f-43a8-852b-43b0596f8f5d.pptx'

[[journal.entries]]
time = "2026-05-04T17:59:17.139206500+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\a.txt'
destination = 'C:\Users\Admin\Desktop\Test\Docs\a.txt'

[[journal.entries]]
time = "2026-05-04T17:59:17.139222700+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\b6a14e88-d31b-4d8e-8b2b-ce2c7e9b5919.docx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\b6a14e88-d31b-4d8e-8b2b-ce2c7e9b5919.docx'

[[journal.entries]]
time = "2026-05-04T17:59:17.139238300+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\BoardingCard_446402878_KUT_FCO.pdf'
destination = 'C:\Users\Admin\Desktop\Test\Docs\BoardingCard_446402878_KUT_FCO.pdf'

[[journal.entries]]
time = "2026-05-04T17:59:17.139254400+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\BoardingCard_446402879_KUT_FCO.pdf'
destination = 'C:\Users\Admin\Desktop\Test\Docs\BoardingCard_446402879_KUT_FCO.pdf'

[[journal.entries]]
time = "2026-05-04T17:59:17.139270600+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\BoardingCard_446402880_KUT_FCO.pdf'
destination = 'C:\Users\Admin\Desktop\Test\Docs\BoardingCard_446402880_KUT_FCO.pdf'

[[journal.entries]]
time = "2026-05-04T17:59:17.139286600+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\BoardingCard_446402881_KUT_FCO.pdf'
destination = 'C:\Users\Admin\Desktop\Test\Docs\BoardingCard_446402881_KUT_FCO.pdf'

[[journal.entries]]
time = "2026-05-04T17:59:17.139303200+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\BoardingCard_455640838_KUT_FCO.pdf'
destination = 'C:\Users\Admin\Desktop\Test\Docs\BoardingCard_455640838_KUT_FCO.pdf'

[[journal.entries]]
time = "2026-05-04T17:59:17.139320900+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\Como desenhar Corpo de Uma Garota Sexy N⁰02 👙.pdf'
destination = 'C:\Users\Admin\Desktop\Test\Docs\Como desenhar Corpo de Uma Garota Sexy N⁰02 👙.pdf'

[[journal.entries]]
time = "2026-05-04T17:59:17.185407100+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\ee3da0bf-8962-4c74-b379-af941e09e4db.pdf'
destination = 'C:\Users\Admin\Desktop\Test\Docs\ee3da0bf-8962-4c74-b379-af941e09e4db.pdf'

[[journal.entries]]
time = "2026-05-04T17:59:17.185435200+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\eInvoice_177998374Z.pdf'
destination = 'C:\Users\Admin\Desktop\Test\Docs\eInvoice_177998374Z.pdf'

[[journal.entries]]
time = "2026-05-04T17:59:17.185452900+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\eInvoice_182816012Z.pdf'
destination = 'C:\Users\Admin\Desktop\Test\Docs\eInvoice_182816012Z.pdf'

[[journal.entries]]
time = "2026-05-04T17:59:17.185474200+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\I შუალედური შეფასება, საზოგადოებრივი აზრის ფორმირება,.docx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\I შუალედური შეფასება, საზოგადოებრივი აზრის ფორმირება,.docx'

[[journal.entries]]
time = "2026-05-04T17:59:17.185490400+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\image_2026-03-21_12-36-41.png'
destination = 'C:\Users\Admin\Desktop\Test\Images\image_2026-03-21_12-36-41.png'

[[journal.entries]]
time = "2026-05-04T17:59:17.185505900+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\image_2026-04-14_18-05-42.png'
destination = 'C:\Users\Admin\Desktop\Test\Images\image_2026-04-14_18-05-42.png'

[[journal.entries]]
time = "2026-05-04T17:59:17.185523800+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\Reservation Details - HMNM3HAS9N.pdf'
destination = 'C:\Users\Admin\Desktop\Test\Docs\Reservation Details - HMNM3HAS9N.pdf'

[[journal.entries]]
time = "2026-05-04T17:59:17.185542100+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\Reservation Details - HMPP9WJSZN-1.pdf'
destination = 'C:\Users\Admin\Desktop\Test\Docs\Reservation Details - HMPP9WJSZN-1.pdf'

[[journal.entries]]
time = "2026-05-04T17:59:17.185559900+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\Reservation Details - HMPP9WJSZN.pdf'
destination = 'C:\Users\Admin\Desktop\Test\Docs\Reservation Details - HMPP9WJSZN.pdf'

[[journal.entries]]
time = "2026-05-04T17:59:17.185577700+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\Reservation Details - HMZ2F2MJME.pdf'
destination = 'C:\Users\Admin\Desktop\Test\Docs\Reservation Details - HMZ2F2MJME.pdf'

[[journal.entries]]
time = "2026-05-04T17:59:17.185595600+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\Reservation Details - HMZ9BEPJHZ.pdf'
destination = 'C:\Users\Admin\Desktop\Test\Docs\Reservation Details - HMZ9BEPJHZ.pdf'

[[journal.entries]]
time = "2026-05-04T17:59:17.185611+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\Screenshot_2026-02-06-13-56-01-981_com.facebook.orca.jpg'
destination = 'C:\Users\Admin\Desktop\Test\Images\Screenshot_2026-02-06-13-56-01-981_com.facebook.orca.jpg'

[[journal.entries]]
time = "2026-05-04T17:59:17.185629400+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\Spiritual_Well-Being_in_Sport_and_Exercise_Psychol.pdf'
destination = 'C:\Users\Admin\Desktop\Test\Docs\Spiritual_Well-Being_in_Sport_and_Exercise_Psychol.pdf'

[[journal.entries]]
time = "2026-05-04T17:59:17.185647500+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\Thesis Defense Presentation.pptx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\Thesis Defense Presentation.pptx'

[[journal.entries]]
time = "2026-05-04T17:59:17.185668500+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\Uldis_Zarins_Sandis_Kondrats_-_Anatomy_for_sculptors_rus.pdf'
destination = 'C:\Users\Admin\Desktop\Test\Docs\Uldis_Zarins_Sandis_Kondrats_-_Anatomy_for_sculptors_rus.pdf'

[[journal.entries]]
time = "2026-05-04T17:59:17.185688100+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\Week 3_Literature Review_Revised.pptx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\Week 3_Literature Review_Revised.pptx'

[[journal.entries]]
time = "2026-05-04T17:59:17.185706500+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\wera.docx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\wera.docx'

[[journal.entries]]
time = "2026-05-04T17:59:17.185728+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\ბაირამოვი_გობეჯიშვილი_საბოლო ნაშრომი.pptx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\ბაირამოვი_გობეჯიშვილი_საბოლო ნაშრომი.pptx'

[[journal.entries]]
time = "2026-05-04T17:59:17.185747+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\დდდსა.docx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\დდდსა.docx'

[[journal.entries]]
time = "2026-05-04T17:59:17.185768+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\კორპორატიული ბლოგი ა.ჯ_რ.ბ.docx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\კორპორატიული ბლოგი ა.ჯ_რ.ბ.docx'

[[journal.entries]]
time = "2026-05-04T17:59:17.185789900+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\ლიტერატურის მიმოხილვა_სტრუქტურა.docx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\ლიტერატურის მიმოხილვა_სტრუქტურა.docx'

[[journal.entries]]
time = "2026-05-04T17:59:17.185810200+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\ნაშრომი პრეზენტაცია.docx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\ნაშრომი პრეზენტაცია.docx'

[[journal.entries]]
time = "2026-05-04T17:59:17.185830400+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\პრეზენტაცია.pptx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\პრეზენტაცია.pptx'

[[journal.entries]]
time = "2026-05-04T17:59:17.185850100+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\პრეზო რეზო.pptx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\პრეზო რეზო.pptx'

[[journal.entries]]
time = "2026-05-04T17:59:17.185871800+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\რაულ ბაირამოვი შუალედური ნაშრომი.docx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\რაულ ბაირამოვი შუალედური ნაშრომი.docx'

[[journal.entries]]
time = "2026-05-04T17:59:17.185893900+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\რაულ_ბაირამოვი_ალტა.docx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\რაულ_ბაირამოვი_ალტა.docx'

[[journal.entries]]
time = "2026-05-04T17:59:17.185917400+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\საბოლოო ნაშრომი_ბაირამოვი_გობეჯიშვილი.docx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\საბოლოო ნაშრომი_ბაირამოვი_გობეჯიშვილი.docx'

[[journal.entries]]
time = "2026-05-04T17:59:17.185938+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\სპორტი დავალება რ (1).docx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\სპორტი დავალება რ (1).docx'

[[journal.entries]]
time = "2026-05-04T17:59:17.185958900+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\სპორტის დავალება #1.docx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\სპორტის დავალება #1.docx'

[[journal.entries]]
time = "2026-05-04T17:59:17.185980100+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\ტექსტი პრეზენტაციის.docx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\ტექსტი პრეზენტაციის.docx'

[[journal.entries]]
time = "2026-05-04T17:59:17.186001600+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\ცნობა - ბაირამოვი რაულ.pdf'
destination = 'C:\Users\Admin\Desktop\Test\Docs\ცნობა - ბაირამოვი რაულ.pdf'

[[journal.entries]]
time = "2026-05-04T17:59:17.186024400+04:00"
action_type = "Automatic"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\წერითი წარდგენა რაულ ბაირამოვი.docx'
destination = 'C:\Users\Admin\Desktop\Test\Docs\წერითი წარდგენა რაულ ბაირამოვი.docx'

[[journal.entries]]
time = "2026-05-04T20:05:29.585631600+04:00"
action_type = "Manual"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\Art_Anatomy_Learned_From_Sketches_スケッチで学ぶ美術解剖学.rar'
destination = 'C:\Users\Admin\Desktop\Test\Archives\Art_Anatomy_Learned_From_Sketches_スケッチで学ぶ美術解剖学.rar'

[[journal.entries]]
time = "2026-05-04T20:05:29.602355900+04:00"
action_type = "Manual"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\Loomis.zip'
destination = 'C:\Users\Admin\Desktop\Test\Archives\Loomis.zip'

[[journal.entries]]
time = "2026-05-04T20:05:29.602380900+04:00"
action_type = "Manual"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\Rebelle5.1.1Pro.rar'
destination = 'C:\Users\Admin\Desktop\Test\Archives\Rebelle5.1.1Pro.rar'

[[journal.entries]]
time = "2026-05-04T20:05:29.602395800+04:00"
action_type = "Manual"

[journal.entries.action.Moved]
source = 'C:\Users\Admin\Desktop\Test\slint.zip'
destination = 'C:\Users\Admin\Desktop\Test\Archives\slint.zip'
